= Release Notes Generation Tool (RLGEN)
:author: Pantelis Tzamalis
:email: tzamalis@ceid.upatras.gr

== Comments

=== Comment 1

* Text:

** Created attachment 8579049
Screenshot - 3_17_2015 , 5_32_36 PM.jpg

User Agent: Mozilla/5.0 (Windows NT 6.1; WOW64; rv:36.0) Gecko/20100101 Firefox/36.0 SeaMonkey/2.33
Build ID: 20150308222025

Steps to reproduce:

Prior to print ... check print preview on screen. This happens on multiple printers.


Actual results:

Paper size shrunk to less than half while text stays large creating multiple pages


Expected results:

Should show normal single page display. Changed setting in Windows 7 printers for letter default in all printers

* Author: bestgroup@lvcoxmail.com

* Created at: 2015-03-18T00:38:16Z

* Bug ID: 1144467

=== Comment 2

* Text:

** I tried to confirm this issue but failed. Please give some more steps to reproduce this issue.

I assume that nothing was printed or previewed since Seamonkey (SM) was started. When Print Preview is opened SM uses the paper setting from the Windows Default Printer. 

To address your problem first make sure that the Default Printer is set to Letter page format and then start SM.

* Author: hb@calen.de

* Created at: 2015-03-22T19:51:26Z

* Bug ID: 1144467

=== Comment 3

* Text:

** Resolved per whiteboard

* Author: pppx@i.com.ua

* Created at: 2015-04-22T00:10:21Z

* Bug ID: 1144467

* No comments are available at this time.



----------
Report time: 2019-07-01 01:26:37.950785


